// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckForUpdate() {
  return window['go']['service']['preferencesService']['CheckForUpdate']();
}

export function GetAppVersion() {
  return window['go']['service']['preferencesService']['GetAppVersion']();
}

export function GetFontList() {
  return window['go']['service']['preferencesService']['GetFontList']();
}

export function GetPreferences() {
  return window['go']['service']['preferencesService']['GetPreferences']();
}

export function GetWindowPosition(arg1) {
  return window['go']['service']['preferencesService']['GetWindowPosition'](arg1);
}

export function GetWindowSize() {
  return window['go']['service']['preferencesService']['GetWindowSize']();
}

export function RestorePreferences() {
  return window['go']['service']['preferencesService']['RestorePreferences']();
}

export function SaveWindowPosition(arg1, arg2) {
  return window['go']['service']['preferencesService']['SaveWindowPosition'](arg1, arg2);
}

export function SaveWindowSize(arg1, arg2, arg3) {
  return window['go']['service']['preferencesService']['SaveWindowSize'](arg1, arg2, arg3);
}

export function SetAppVersion(arg1) {
  return window['go']['service']['preferencesService']['SetAppVersion'](arg1);
}

export function SetPreferences(arg1) {
  return window['go']['service']['preferencesService']['SetPreferences'](arg1);
}

export function Startup(arg1) {
  return window['go']['service']['preferencesService']['Startup'](arg1);
}

export function UpdatePreferences(arg1) {
  return window['go']['service']['preferencesService']['UpdatePreferences'](arg1);
}
